[platformio]
default_envs = esp01_1m

[env:esp01_1m]
platform = espressif8266
board = esp01
framework = arduino
monitor_speed = 115200
upload_speed = 115200

lib_deps =
    adafruit/Adafruit ADS1X15 @ ^2.5.0
    adafruit/Adafruit SSD1306 @ ^2.5.13
    adafruit/Adafruit GFX Library @ ^1.11.11
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21.5

